# Site settings
title: argmin gravitas
fmtTitle: <span style="font-size:15pt">argmin</span>&nbsp; gravitas
email: g@gleech.org  
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://gleech.org # the base hostname & protocol for your site
github_username:  g-leech

# Build settings
markdown: kramdown
