# Site settings
title: grit / technicalities
email: g[dot]leech.08[at]aberdeen.ac.uk  
baseurl: "http://gleech.org/" # the subpath of your site, e.g. /blog/
url: http://gleech.org/ # the base hostname & protocol for your site
github_username:  gavin-leech

# Build settings
markdown: kramdown
