# Site settings
title: technicalities and finings
email: g[dot]leech.08[at]aberdeen.ac.uk  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://technicalities.netlify.com/about/" # the base hostname & protocol for your site
github_username:  gavin-leech

# Build settings
markdown: kramdown
