# Site settings
title: technicalities, finings
email: aberdeen.ac.uk, g.leech.08@  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://technicalities.netlify.com/about/" # the base hostname & protocol for your site
github_username:  gavin-leech

# Build settings
markdown: kramdown
