# Site settings
title: argmin gravitas
fmtTitle: <span style="font-size:16pt">argmin</span> gravitas
email: g@gleech.org  
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.gleech.org # the base hostname & protocol for your site
github_username:  g-leech


# Build settings
markdown: kramdown
